## Python Libraries for DNN

<strong>TENSORFLOW </strong>:<br>
TensorFlow is an end-to-end open-source machine learning platform with a focus on deep neural networks. Deep learning is a subtype of machine learning that analyses massive amounts of unstructured data.<br>
Some of the main features are:<br>
Flexible architecture and framework., Runs on a variety of computational platforms. , Abstraction capabilities, Manages deep neural networks. 

In [ ]:
import tensorflow as tf
print("Tensorflow version:",tf.__version__)

Tensorflow version: 2.9.2


<strong>MATPLOTLIB </strong>:<br> 
Matplotlib is a Python library that helps in visualizing and analyzing the data and helps in better understanding of the data with the help of 
graphical, pictorial visualizations that can be simulated using the matplotlib library.<br>
Matplotlib is a comprehensive library for static, animated and interactive visualizations<br>



<strong> Theano</strong>:<br>
Theano is a Python library that allows us to evaluate mathematical operations including multi-dimensional arrays so easily.<br>
It is mostly used in building Deep Learning Projects. It works a way more faster on Graphics Processing Unit (GPU) rather than on CPU.<br>
Some main features of theano are: <br>
Built-in validation and unit testing tools, High-performing mathematical computations, Fast and stable evaluations, Data-intensive calculations.

<strong>PyTorch</strong> :<br> 
PyTorch is de ned as an open source machine learning library for Python. It is used for applications such as natural language processing.<br>
PyTorch redesigns and implements Torch in Python while sharing the same core C libraries for the backend code. PyTorch developers tuned this back-end 
code to run Python efficiently.<br>
Some of the main features are:<br>
Statistical distribution and operations, Control over datasets, Development of deep learning models, Highly flexible.

In [ ]:
import torch
shape=(2,3,) 
rand_tensor=torch.rand(shape) 
ones_tensor=torch.ones(shape) 
zeros_tensor=torch.zeros(shape)
print(f"Random Tensor:\n{rand_tensor}\n") 
print(f"Ones Tensor:\n{ones_tensor}\n") 
print(f"Zeros Tensor:\n{zeros_tensor}\n")

Random Tensor:
tensor([[0.2873, 0.0983, 0.7369],
        [0.4039, 0.1678, 0.4884]])

Ones Tensor:
tensor([[1., 1., 1.],
        [1., 1., 1.]])

Zeros Tensor:
tensor([[0., 0., 0.],
        [0., 0., 0.]])



<strong>PANDAS</strong> :<br> 
Pandas is an open-source library that is made mainly for working with relational or labeled data both easily and intuitively.<br>
It provides various data structures and operations for manipulating numerical data and time series.<br>
some of the main features are:<br>
Indexing of data, Data alignment, Merging/joining of datasets, Data manipulation and analysis.


In [ ]:
import pandas as pd 
data={"country":["brazil","russia"],"capital":["brasilia","moscow"]} 
data_table=pd.DataFrame(data) 
print(data_table)

  country   capital
0  brazil  brasilia
1  russia    moscow


<strong>Numpy</strong><br>
1. Numpy is a Python library
2. Numpy is used for working with arrays
3. Numpy is short for "Numerical python"<br>
Some main features of numpy are:<br><br>
Shape manipulation, high performance N-dimensional array object, data cleaning/manipulation, statistical operations and linear algebra 

In [ ]:
import numpy as np
arr = np.array ([[1,2,3,4,5],[6,7,8,9,10]])
print(arr)
print("Array is of type: ", type(arr)) 
print("No. of dimensions: ", arr.ndim) 
print("Shape of array: ", arr.shape)
print("Size of array: ", arr.size) 
print("Array stores elements of type: ", arr.dtype)


[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
Array is of type:  <class 'numpy.ndarray'>
No. of dimensions:  2
Shape of array:  (2, 5)
Size of array:  10
Array stores elements of type:  int64


<strong>Scipy</strong><br>
SciPy is a scienti c computation library that uses NumPy underneath. SciPy stands for Scienti c Python.<br>
It provides more utility functions for optimization, stats and signal processing. Like NumPy, SciPy is open source so we can use it freely<br>
It is user friendly, data visualization and manipulation, scientific and technical analysis and computes large datasets


In [ ]:
from scipy import constants 
print(constants.pi)

3.141592653589793


<strong>SCIKIT-LEARN</strong> :<br>
Scikit-learn is an open source data analysis library, and the gold standard for Machine Learning (ML) in the Python ecosystem.<br>
Key concepts and features include: Algorithmic decision-making methods, including: Classi cation: identifying and categorizing data based on patterns,Data classification and modeling, End-to-end machine learning algorithms, Pre-processing of data, Model selection.


In [ ]:
from sklearn import datasets 
digits=datasets.load_digits() 
print(digits.data.shape)

(1797, 64)


In [ ]:
from sklearn.datasets import load_iris 
iris = load_iris()
X = iris.data 
y = iris.target
feature_names = iris.feature_names 
target_names = iris.target_names
print("Feature names:", feature_names) 
print("Target names:", target_names)
print("\nType of X is:", type(X))
print("\nFirst 5 rows of X:\n", X[:5])


Feature names: ['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']
Target names: ['setosa' 'versicolor' 'virginica']

Type of X is: <class 'numpy.ndarray'>

First 5 rows of X:
 [[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]]
