## Principle component analysis

A program to find multiple PCA from single data set and find PCA with maximum data spread


In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.datasets import load_iris
from sklearn.decomposition import PCA

In [ ]:
# Loading the dataset
iris = load_iris()

In [ ]:
# Loading data into dataframe
df = pd.DataFrame(data=iris['data'], columns=iris['feature_names'])

In [ ]:
# Finding multiple PCA
pca = PCA(n_components=4)
pca.fit(df)

PCA(n_components=4)

In [ ]:
# Finding the PCA with the maximum spread
variances = pca.explained_variance_
max_variance_index = np.argmax(variances)
max_variance_component = pca.components_[max_variance_index]
print("All the PCA are as follows: \n",pca.components_)
print('And the PCA with the maximum spread is: \n', max_variance_component)

All the PCA are as follows: 
 [[ 0.36138659 -0.08452251  0.85667061  0.3582892 ]
 [ 0.65658877  0.73016143 -0.17337266 -0.07548102]
 [-0.58202985  0.59791083  0.07623608  0.54583143]
 [-0.31548719  0.3197231   0.47983899 -0.75365743]]
And the PCA with the maximum spread is: 
 [ 0.36138659 -0.08452251  0.85667061  0.3582892 ]
